In [1]:
!pip install pandas

In [5]:
import pandas as pd

In [16]:
df = pd.read_csv('Downloads\Car_Insurance.csv')

In [18]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [19]:
df.iloc[:,:]

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [20]:
df.iloc[:,0]

0    Toyota
1      Ford
2    Toyota
3    Nissan
4    Nissan
5      Ford
6    Toyota
7    Nissan
8    Toyota
9    Nissan
Name: Make, dtype: object

In [21]:
df.iloc[2,0]

'Toyota'

In [22]:
df.iloc[1,0]

'Ford'

In [23]:
df.iloc[5,:]

Make          Ford
Age            8.0
Mileage    73000.0
Fuel           NaN
Gearbox          M
Colour       Green
Claimed         No
Name: 5, dtype: object

In [24]:
df['Age']

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [25]:
df.Age

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [29]:
df.iloc[0,1]

2.0

In [30]:
df.iloc[:,0].unique()

array(['Toyota', 'Ford', 'Nissan'], dtype=object)

In [36]:
df.iloc[:,0].value_counts()

Toyota    4
Nissan    4
Ford      2
Name: Make, dtype: int64

In [38]:
df.iloc[:,0].isin(['Nissan'])

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8    False
9     True
Name: Make, dtype: bool

In [42]:
df.iloc[:,0].isin(['Toyota'])

0     True
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8     True
9    False
Name: Make, dtype: bool

In [44]:
df.iloc[:,0].isin(['Skoda'])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Make, dtype: bool

In [45]:
df.iloc[:,1].sort_values()

0     2.0
4     2.0
1     4.0
9     7.0
5     8.0
3    13.0
8    13.0
2    15.0
7    20.0
6     NaN
Name: Age, dtype: float64

In [46]:
df.iloc[:,1].sort_values(ascending=False)

7    20.0
2    15.0
3    13.0
8    13.0
5     8.0
9     7.0
1     4.0
0     2.0
4     2.0
6     NaN
Name: Age, dtype: float64

In [47]:
df.iloc[:,1].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [48]:
df.iloc[:,1].isnull().values.any()

True

In [49]:
df['Age'].min()

2.0

In [50]:
df['Age'].max()

20.0

In [51]:
df['Age'].mean()

9.333333333333334

In [55]:
!pip install scikit-learn --quiet

In [56]:
import sklearn

In [57]:
df.iloc[:,:]

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [58]:
df.isnull().sum()

Make       0
Age        1
Mileage    1
Fuel       1
Gearbox    1
Colour     1
Claimed    0
dtype: int64

In [59]:
pwd

'C:\\Users\\home'

In [60]:
from sklearn.impute import SimpleImputer

In [61]:
# numerical variables
# strategies: mean, median, most_frequent, constant
import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='mean')
numImputer = numImputer.fit(df[['Age','Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr

array([[2.00000000e+00, 2.70000000e+04],
       [4.00000000e+00, 3.05000000e+04],
       [1.50000000e+01, 1.20000000e+05],
       [1.30000000e+01, 5.30000000e+04],
       [2.00000000e+00, 6.47222222e+04],
       [8.00000000e+00, 7.30000000e+04],
       [9.33333333e+00, 1.38000000e+05],
       [2.00000000e+01, 3.80000000e+04],
       [1.30000000e+01, 6.70000000e+04],
       [7.00000000e+00, 3.60000000e+04]])

In [62]:
# numerical variables
# strategies: mean, median, most_frequent, constant
import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='median')
numImputer = numImputer.fit(df[['Age','Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr

array([[2.00e+00, 2.70e+04],
       [4.00e+00, 3.05e+04],
       [1.50e+01, 1.20e+05],
       [1.30e+01, 5.30e+04],
       [2.00e+00, 5.30e+04],
       [8.00e+00, 7.30e+04],
       [8.00e+00, 1.38e+05],
       [2.00e+01, 3.80e+04],
       [1.30e+01, 6.70e+04],
       [7.00e+00, 3.60e+04]])

In [63]:
# numerical variables
# strategies: mean, median, most_frequent, constant
import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
numImputer = numImputer.fit(df[['Age','Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr

array([[2.00e+00, 2.70e+04],
       [4.00e+00, 3.05e+04],
       [1.50e+01, 1.20e+05],
       [1.30e+01, 5.30e+04],
       [2.00e+00, 2.70e+04],
       [8.00e+00, 7.30e+04],
       [2.00e+00, 1.38e+05],
       [2.00e+01, 3.80e+04],
       [1.30e+01, 6.70e+04],
       [7.00e+00, 3.60e+04]])

In [64]:
# numerical variables
# strategies: mean, median, most_frequent, constant
import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value=-1)
numImputer = numImputer.fit(df[['Age','Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr

array([[ 2.00e+00,  2.70e+04],
       [ 4.00e+00,  3.05e+04],
       [ 1.50e+01,  1.20e+05],
       [ 1.30e+01,  5.30e+04],
       [ 2.00e+00, -1.00e+00],
       [ 8.00e+00,  7.30e+04],
       [-1.00e+00,  1.38e+05],
       [ 2.00e+01,  3.80e+04],
       [ 1.30e+01,  6.70e+04],
       [ 7.00e+00,  3.60e+04]])

In [65]:
# numerical variables
# strategies: mean, median, most_frequent, constant
import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='mean')
numImputer = numImputer.fit(df[['Age','Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr

array([[2.00000000e+00, 2.70000000e+04],
       [4.00000000e+00, 3.05000000e+04],
       [1.50000000e+01, 1.20000000e+05],
       [1.30000000e+01, 5.30000000e+04],
       [2.00000000e+00, 6.47222222e+04],
       [8.00000000e+00, 7.30000000e+04],
       [9.33333333e+00, 1.38000000e+05],
       [2.00000000e+01, 3.80000000e+04],
       [1.30000000e+01, 6.70000000e+04],
       [7.00000000e+00, 3.60000000e+04]])